name: MyBot
on:
  pull_request_target:
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.hesd.sha }}
      - name: Do stuff
        run: ls -l
      - name: Scan
        uses: SonarSource/docker-sonarqube/.github/workflows/next-scan.yml@7853595415e8ddf259b5003be8f1caabab3b1717
